TRAIN:
  ENABLE: True
  DATASET: vggsound3d
  BATCH_SIZE: 48
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  INPUT_CHANNEL_NUM: [1, 1]
AUDIO_DATA:
  SAMPLING_RATE: 16000
#  CLIP_SECS: 5.119
#  NUM_FREQUENCIES: 128
#  wNUM_FRAMES: 512
#  WINDOW_LENGTH: 20
#  HOP_LENGTH: 10

  CLIP_SECS: 1.28
  NUM_FREQUENCIES: 256
  NUM_FRAMES: 256
  WINDOW_LENGTH: 10
  HOP_LENGTH: 5
BN:
  USE_PRECISE_STATS: False
  FREEZE: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0001
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 8.0
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: [309,]
  MODEL_NAME: AudioMViT
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: vggsound3d
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 2
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
LOG_MODEL_INFO: False
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
